#!/bin/bash

set -ex

compile-mc() {
    /home/bjorn/rv/toolchain/bin/riscv32-unknown-linux-gnu-gcc -g \
							       -march=${2} -mabi=ilp32 \
							       -mcmodel=medlow -c builtins.c -o builtins-${2}.o
    /home/bjorn/rv/toolchain/bin/riscv32-unknown-linux-gnu-gcc -g -march=${2} -mabi=ilp32 \
							       -DMC_BENCH \
							       -static -mcmodel=medlow -${1} -nostdlib -nostartfiles \
							       -ffreestanding -flto -Wl,--gc-sections -I../mc ../mc/monocypher.c \
							       ../mc/optional/monocypher-ed25519.c signtest.c -o mc-${1}-${2} \
							       -lgcc builtins-${2}.o
}

compile-tn() {
    /home/bjorn/rv/toolchain/bin/riscv32-unknown-linux-gnu-gcc -g \
							       -march=${2} -mabi=ilp32 \
							       -mcmodel=medlow -c builtins.c -o builtins-${2}.o
    /home/bjorn/rv/toolchain/bin/riscv32-unknown-linux-gnu-gcc -g -march=${2} -mabi=ilp32 \
							       -DTN_BENCH \
							       -static -mcmodel=medlow -${1} -nostdlib -nostartfiles \
							       -ffreestanding -flto -Wl,--gc-sections -I../tn ../tn/tweetnacl.c \
							       signtest.c -o tn-${1}-${2} -lgcc builtins-${2}.o
}

compile-mc Os rv32i
compile-mc Os rv32im
compile-mc Os rv32ic
compile-mc Os rv32imc

compile-tn Os rv32i
compile-tn Os rv32im
compile-tn Os rv32ic
compile-tn Os rv32imc

size mc-*
size tn-*

rm mc-*
rm tn-*
rm *.o
